import './styles.css'
import type { ThemePackage } from '@/lib/types'
import SteampunkBackgroundEffects from './BackgroundEffects'

export const steampunkTheme: ThemePackage = {
  id: 'steampunk',
  name: 'Steampunk',
  description: 'Victorian industrial meets brass machinery – copper tones, mechanical aesthetics, ornate details',
  author: 'Neuroklast',
  version: '1.0.0',
  access: 'premium',
  layout: {
    heroVariant: 'default',
    loadingScreen: 'minimal',
    navigationStyle: 'clean',
  },
  typography: {
    heading: "'Cinzel', serif",
    body: "'Lora', serif",
    mono: "'Courier Prime', monospace",
  },
  effects: {
    overlayEffects: {
      scanlines: { enabled: false, intensity: 0 },
      crt: { enabled: false, intensity: 0 },
      noise: { enabled: true, intensity: 0.2 },
      vignette: { enabled: true, intensity: 0.6 },
      chromatic: { enabled: false, intensity: 0 },
      dotMatrix: { enabled: true, intensity: 0.1 },
    },
    animationSettings: {
      glitchEnabled: false,
      scanlineEnabled: false,
      chromaticEnabled: false,
      crtEnabled: false,
      noiseEnabled: false,
      circuitBackgroundEnabled: false,
      crtOverlayOpacity: 0,
      crtVignetteOpacity: 0,
      overlayTransitionEnabled: false,
    },
  },
  borderRadius: 0.25,
  animationsEnabled: true,
  colorPresets: [
    {
      id: 'brass-copper',
      name: 'Brass & Copper',
      description: 'Warm copper on dark brown',
      colors: {
        primary: 'oklch(0.62 0.12 50)',
        accent: 'oklch(0.72 0.14 55)',
        background: 'oklch(0.10 0.03 40)',
        card: 'oklch(0.15 0.03 40)',
        foreground: 'oklch(0.92 0.04 60)',
        mutedForeground: 'oklch(0.58 0.06 50)',
        border: 'oklch(0.25 0.05 48)',
        secondary: 'oklch(0.18 0.03 42)',
      },
    },
    {
      id: 'ironworks',
      name: 'Ironworks',
      description: 'Dark iron grey with orange sparks',
      colors: {
        primary: 'oklch(0.65 0.14 40)',
        accent: 'oklch(0.75 0.16 45)',
        background: 'oklch(0.08 0.01 260)',
        card: 'oklch(0.13 0.01 260)',
        foreground: 'oklch(0.90 0.02 50)',
        mutedForeground: 'oklch(0.55 0.04 50)',
        border: 'oklch(0.22 0.02 260)',
        secondary: 'oklch(0.16 0.01 260)',
      },
    },
    {
      id: 'aged-paper',
      name: 'Aged Paper',
      description: 'Sepia tones',
      colors: {
        primary: 'oklch(0.55 0.07 70)',
        accent: 'oklch(0.65 0.09 75)',
        background: 'oklch(0.88 0.04 80)',
        card: 'oklch(0.82 0.04 80)',
        foreground: 'oklch(0.18 0.04 55)',
        mutedForeground: 'oklch(0.45 0.05 65)',
        border: 'oklch(0.70 0.05 75)',
        secondary: 'oklch(0.78 0.03 78)',
      },
    },
    {
      id: 'verdigris',
      name: 'Verdigris',
      description: 'Oxidized copper green',
      colors: {
        primary: 'oklch(0.58 0.12 175)',
        accent: 'oklch(0.68 0.14 175)',
        background: 'oklch(0.08 0.02 175)',
        card: 'oklch(0.12 0.02 175)',
        foreground: 'oklch(0.90 0.03 165)',
        mutedForeground: 'oklch(0.55 0.06 175)',
        border: 'oklch(0.20 0.06 175)',
        secondary: 'oklch(0.14 0.03 173)',
      },
    },
    {
      id: 'mahogany-gold',
      name: 'Mahogany & Gold',
      description: 'Rich mahogany with gold accents',
      colors: {
        primary: 'oklch(0.70 0.12 80)',
        accent: 'oklch(0.80 0.14 85)',
        background: 'oklch(0.12 0.04 30)',
        card: 'oklch(0.17 0.04 30)',
        foreground: 'oklch(0.93 0.04 75)',
        mutedForeground: 'oklch(0.60 0.05 55)',
        border: 'oklch(0.28 0.06 40)',
        secondary: 'oklch(0.20 0.04 35)',
      },
    },
  ],
  defaultPresetId: 'brass-copper',
  defaultColors: {
    primary: 'oklch(0.62 0.12 50)',
    accent: 'oklch(0.72 0.14 55)',
    background: 'oklch(0.10 0.03 40)',
    card: 'oklch(0.15 0.03 40)',
    foreground: 'oklch(0.92 0.04 60)',
    mutedForeground: 'oklch(0.58 0.06 50)',
    border: 'oklch(0.25 0.05 48)',
    secondary: 'oklch(0.18 0.03 42)',
  },
  defaultFonts: {
    heading: "'Cinzel', serif",
    body: "'Lora', serif",
    mono: "'Courier Prime', monospace",
  },
  animations: [
    { id: 'noise', label: 'Texture Noise', defaultEnabled: true, defaultIntensity: 0.2 },
    { id: 'vignette', label: 'Vignette', defaultEnabled: true, defaultIntensity: 0.6 },
    { id: 'dotMatrix', label: 'Dot Matrix', defaultEnabled: true, defaultIntensity: 0.1 },
  ],
  customizability: { customColors: true, customFonts: true, adjustEffects: true },
  slots: {
    BackgroundEffects: SteampunkBackgroundEffects,
  },
}
