import type { ThemePackage } from '@/lib/types'

export const artDecoCyberpunkTheme: ThemePackage = {
  id: 'art-deco-cyberpunk',
  name: 'Art Deco Cyberpunk',
  description: '1920s Art Deco meets future tech – geometric gold leaf patterns on black, angular symmetry',
  author: 'Neuroklast',
  version: '1.0.0',
  access: 'premium',
  layout: {
    heroVariant: 'default',
    loadingScreen: 'minimal',
    navigationStyle: 'clean',
  },
  typography: {
    heading: "'Poiret One', sans-serif",
    body: "'Raleway', sans-serif",
    mono: "'Courier Prime', monospace",
  },
  effects: {
    overlayEffects: {
      scanlines: { enabled: false, intensity: 0 },
      crt: { enabled: false, intensity: 0 },
      noise: { enabled: true, intensity: 0.05 },
      vignette: { enabled: true, intensity: 0.5 },
      chromatic: { enabled: false, intensity: 0 },
      dotMatrix: { enabled: true, intensity: 0.15 },
    },
    animationSettings: {
      glitchEnabled: false,
      scanlineEnabled: false,
      chromaticEnabled: false,
      crtEnabled: false,
      noiseEnabled: false,
      circuitBackgroundEnabled: false,
      crtOverlayOpacity: 0,
      crtVignetteOpacity: 0,
      overlayTransitionEnabled: true,
    },
  },
  borderRadius: 0,
  animationsEnabled: true,
  colorPresets: [
    {
      id: 'gold-leaf',
      name: 'Gold Leaf',
      description: 'Pure gold on absolute black',
      colors: {
        primary: 'oklch(0.75 0.12 85)',
        accent: 'oklch(0.85 0.14 90)',
        background: 'oklch(0.02 0 0)',
        card: 'oklch(0.06 0.01 60)',
        foreground: 'oklch(0.95 0.03 80)',
        mutedForeground: 'oklch(0.60 0.05 80)',
        border: 'oklch(0.25 0.06 75)',
        secondary: 'oklch(0.10 0.01 65)',
      },
    },
    {
      id: 'platinum',
      name: 'Platinum',
      description: 'Silver on charcoal',
      colors: {
        primary: 'oklch(0.80 0.01 240)',
        accent: 'oklch(0.88 0.01 240)',
        background: 'oklch(0.08 0.01 240)',
        card: 'oklch(0.12 0.01 240)',
        foreground: 'oklch(0.95 0 0)',
        mutedForeground: 'oklch(0.60 0.01 240)',
        border: 'oklch(0.25 0.02 240)',
        secondary: 'oklch(0.16 0.01 240)',
      },
    },
    {
      id: 'emerald-deco',
      name: 'Emerald Deco',
      description: 'Deep green on black',
      colors: {
        primary: 'oklch(0.55 0.15 145)',
        accent: 'oklch(0.65 0.17 145)',
        background: 'oklch(0.03 0.01 150)',
        card: 'oklch(0.07 0.02 150)',
        foreground: 'oklch(0.92 0.03 140)',
        mutedForeground: 'oklch(0.55 0.06 145)',
        border: 'oklch(0.18 0.06 145)',
        secondary: 'oklch(0.10 0.03 148)',
      },
    },
    {
      id: 'ruby',
      name: 'Ruby',
      description: 'Deep red on black',
      colors: {
        primary: 'oklch(0.50 0.18 20)',
        accent: 'oklch(0.60 0.20 20)',
        background: 'oklch(0.03 0.01 15)',
        card: 'oklch(0.07 0.02 15)',
        foreground: 'oklch(0.95 0.02 30)',
        mutedForeground: 'oklch(0.55 0.05 20)',
        border: 'oklch(0.18 0.08 20)',
        secondary: 'oklch(0.10 0.03 18)',
      },
    },
    {
      id: 'ivory-tower',
      name: 'Ivory Tower',
      description: 'Warm white on dark',
      colors: {
        primary: 'oklch(0.90 0.03 85)',
        accent: 'oklch(0.95 0.02 80)',
        background: 'oklch(0.10 0.01 60)',
        card: 'oklch(0.14 0.01 60)',
        foreground: 'oklch(0.96 0.02 80)',
        mutedForeground: 'oklch(0.65 0.03 75)',
        border: 'oklch(0.25 0.02 70)',
        secondary: 'oklch(0.18 0.02 65)',
      },
    },
  ],
  defaultPresetId: 'gold-leaf',
  customizability: { customColors: true, customFonts: true, adjustEffects: true },
  slots: {},
}
