import type { ThemePackage } from '@/lib/types'

export const cyberpunkTheme: ThemePackage = {
  id: 'cyberpunk',
  name: 'Cyberpunk',
  description: 'Dark industrial aesthetic with crimson red neon accents',
  author: 'Neuroklast',
  version: '1.0.0',
  access: 'premium',
  layout: {
    heroVariant: 'glitch-parallax',
    loadingScreen: 'cyberpunk',
    navigationStyle: 'cyberpunk-hud',
  },
  typography: {
    heading: "'JetBrains Mono', monospace",
    body: "'Space Grotesk', sans-serif",
    mono: "'JetBrains Mono', monospace",
  },
  effects: {
    overlayEffects: {
      scanlines: { enabled: true, intensity: 0.4 },
      crt: { enabled: true, intensity: 0.6 },
      noise: { enabled: true, intensity: 0.15 },
      vignette: { enabled: true, intensity: 0.3 },
      chromatic: { enabled: true, intensity: 0.3 },
      dotMatrix: { enabled: false, intensity: 0 },
    },
    animationSettings: {
      glitchEnabled: true,
      scanlineEnabled: true,
      chromaticEnabled: true,
      crtEnabled: true,
      noiseEnabled: true,
      circuitBackgroundEnabled: true,
      crtOverlayOpacity: 0.6,
      crtVignetteOpacity: 0.3,
      overlayTransitionEnabled: false,
    },
  },
  borderRadius: 0.125,
  animationsEnabled: true,
  colorPresets: [
    {
      id: 'neon-red',
      name: 'Neon Red',
      description: 'Default crimson red neon',
      colors: {
        primary: 'oklch(0.50 0.22 25)',
        accent: 'oklch(0.60 0.24 25)',
        background: 'oklch(0 0 0)',
        card: 'oklch(0.05 0 0)',
        foreground: 'oklch(1 0 0)',
        mutedForeground: 'oklch(0.55 0 0)',
        border: 'oklch(0.15 0 0)',
        secondary: 'oklch(0.10 0 0)',
      },
    },
    {
      id: 'cyber-blue',
      name: 'Cyber Blue',
      description: 'Electric cyber blue',
      colors: {
        primary: 'oklch(0.55 0.22 220)',
        accent: 'oklch(0.65 0.20 210)',
        background: 'oklch(0 0 0)',
        card: 'oklch(0.05 0.01 220)',
        foreground: 'oklch(1 0 0)',
        mutedForeground: 'oklch(0.55 0 0)',
        border: 'oklch(0.15 0.02 220)',
        secondary: 'oklch(0.10 0 0)',
      },
    },
    {
      id: 'toxic-green',
      name: 'Toxic Green',
      description: 'Toxic neon green',
      colors: {
        primary: 'oklch(0.60 0.22 145)',
        accent: 'oklch(0.70 0.20 150)',
        background: 'oklch(0 0 0)',
        card: 'oklch(0.05 0.01 145)',
        foreground: 'oklch(1 0 0)',
        mutedForeground: 'oklch(0.55 0 0)',
        border: 'oklch(0.15 0.02 145)',
        secondary: 'oklch(0.10 0 0)',
      },
    },
    {
      id: 'violet-chrome',
      name: 'Violet Chrome',
      description: 'Deep violet with chrome sheen',
      colors: {
        primary: 'oklch(0.55 0.22 290)',
        accent: 'oklch(0.65 0.20 300)',
        background: 'oklch(0 0 0)',
        card: 'oklch(0.05 0.01 290)',
        foreground: 'oklch(1 0 0)',
        mutedForeground: 'oklch(0.55 0 0)',
        border: 'oklch(0.15 0.02 290)',
        secondary: 'oklch(0.10 0 0)',
      },
    },
    {
      id: 'gold-circuit',
      name: 'Gold Circuit',
      description: 'Circuit board gold',
      colors: {
        primary: 'oklch(0.72 0.15 85)',
        accent: 'oklch(0.80 0.14 90)',
        background: 'oklch(0 0 0)',
        card: 'oklch(0.05 0 0)',
        foreground: 'oklch(1 0 0)',
        mutedForeground: 'oklch(0.55 0 0)',
        border: 'oklch(0.15 0.02 85)',
        secondary: 'oklch(0.10 0 0)',
      },
    },
    {
      id: 'crimson-punk',
      name: 'Crimson Punk',
      description: 'Aggressive crimson punk',
      colors: {
        primary: 'oklch(0.45 0.25 10)',
        accent: 'oklch(0.55 0.26 15)',
        background: 'oklch(0 0 0)',
        card: 'oklch(0.05 0 0)',
        foreground: 'oklch(1 0 0)',
        mutedForeground: 'oklch(0.55 0 0)',
        border: 'oklch(0.15 0 0)',
        secondary: 'oklch(0.10 0 0)',
      },
    },
  ],
  defaultPresetId: 'neon-red',
  customizability: { customColors: true, customFonts: true, adjustEffects: true },
  slots: {},
}
