import type { ThemePackage } from '@/lib/types'

export const vhsRetroTheme: ThemePackage = {
  id: 'vhs-retro',
  name: 'VHS Retro',
  description: 'Analog VHS tape aesthetic – tracking lines, color bleeding, tape distortion',
  author: 'Neuroklast',
  version: '1.0.0',
  access: 'premium',
  layout: {
    heroVariant: 'default',
    loadingScreen: 'minimal',
    navigationStyle: 'clean',
  },
  typography: {
    heading: "'Press Start 2P', monospace",
    body: "'Space Grotesk', sans-serif",
    mono: "'VT323', monospace",
  },
  effects: {
    overlayEffects: {
      scanlines: { enabled: true, intensity: 0.5 },
      crt: { enabled: true, intensity: 0.5 },
      noise: { enabled: true, intensity: 0.4 },
      vignette: { enabled: false, intensity: 0 },
      chromatic: { enabled: true, intensity: 0.4 },
      dotMatrix: { enabled: false, intensity: 0 },
    },
    animationSettings: {
      glitchEnabled: false,
      scanlineEnabled: true,
      chromaticEnabled: true,
      crtEnabled: true,
      noiseEnabled: true,
      circuitBackgroundEnabled: false,
      crtOverlayOpacity: 0.5,
      crtVignetteOpacity: 0,
      overlayTransitionEnabled: false,
    },
  },
  borderRadius: 0,
  animationsEnabled: true,
  colorPresets: [
    {
      id: 'vhs-classic',
      name: 'VHS Classic',
      description: 'Washed-out warm tones with slight yellow-tint',
      colors: {
        primary: 'oklch(0.72 0.10 75)',
        accent: 'oklch(0.80 0.08 80)',
        background: 'oklch(0.06 0.02 60)',
        card: 'oklch(0.10 0.02 60)',
        foreground: 'oklch(0.90 0.04 80)',
        mutedForeground: 'oklch(0.58 0.05 70)',
        border: 'oklch(0.22 0.03 65)',
        secondary: 'oklch(0.14 0.02 62)',
      },
    },
    {
      id: 'tracking-error',
      name: 'Tracking Error',
      description: 'Blue/cyan distorted',
      colors: {
        primary: 'oklch(0.70 0.18 210)',
        accent: 'oklch(0.78 0.16 195)',
        background: 'oklch(0.04 0.02 230)',
        card: 'oklch(0.09 0.03 230)',
        foreground: 'oklch(0.93 0.04 200)',
        mutedForeground: 'oklch(0.55 0.08 210)',
        border: 'oklch(0.20 0.08 220)',
        secondary: 'oklch(0.12 0.04 225)',
      },
    },
    {
      id: 'tape-pause',
      name: 'Tape Pause',
      description: 'High contrast B&W with blue tint',
      colors: {
        primary: 'oklch(0.88 0.02 230)',
        accent: 'oklch(0.95 0.01 220)',
        background: 'oklch(0.05 0.01 230)',
        card: 'oklch(0.10 0.01 230)',
        foreground: 'oklch(0.97 0.01 220)',
        mutedForeground: 'oklch(0.60 0.02 230)',
        border: 'oklch(0.25 0.02 230)',
        secondary: 'oklch(0.15 0.01 230)',
      },
    },
    {
      id: 'ep-mode',
      name: 'EP Mode',
      description: 'Degraded warm colors with heavy noise',
      colors: {
        primary: 'oklch(0.65 0.10 60)',
        accent: 'oklch(0.73 0.08 65)',
        background: 'oklch(0.08 0.03 50)',
        card: 'oklch(0.13 0.03 50)',
        foreground: 'oklch(0.85 0.05 70)',
        mutedForeground: 'oklch(0.52 0.06 60)',
        border: 'oklch(0.22 0.04 55)',
        secondary: 'oklch(0.16 0.03 52)',
      },
    },
  ],
  defaultPresetId: 'vhs-classic',
  customizability: { customColors: true, customFonts: true, adjustEffects: true },
  slots: {},
}
