import './styles.css'
import type { ThemePackage } from '@/lib/types'
import CyberpunkBackgroundEffects from './BackgroundEffects'
import CyberpunkHero from './Hero'
import CyberpunkNavigation from './Navigation'
import CyberpunkFooter from './Footer'
import CyberpunkLoadingScreen from './LoadingScreen'

export const cyberpunkTheme: ThemePackage = {
  id: 'cyberpunk',
  name: 'Cyberpunk',
  description: 'Neon-lit Night City aesthetic — holographic UI, glowing borders, perspective grids',
  author: 'Neuroklast',
  version: '2.0.0',
  access: 'premium',
  layout: {
    heroVariant: 'default',
    loadingScreen: 'cyberpunk',
    navigationStyle: 'default',
  },
  typography: {
    heading: "'Orbitron', sans-serif",
    body: "'Exo 2', sans-serif",
    mono: "'Share Tech Mono', monospace",
  },
  effects: {
    overlayEffects: {
      scanlines: { enabled: false, intensity: 0 },
      crt: { enabled: false, intensity: 0 },
      noise: { enabled: false, intensity: 0 },
      vignette: { enabled: false, intensity: 0 },
      chromatic: { enabled: true, intensity: 0.3 },
      dotMatrix: { enabled: false, intensity: 0 },
    },
    animationSettings: {
      glitchEnabled: false,
      scanlineEnabled: false,
      chromaticEnabled: true,
      crtEnabled: false,
      noiseEnabled: false,
      circuitBackgroundEnabled: false,
      crtOverlayOpacity: 0,
      crtVignetteOpacity: 0,
      overlayTransitionEnabled: true,
    },
  },
  borderRadius: 0.25,
  animationsEnabled: true,
  colorPresets: [
    {
      id: 'night-city-neon',
      name: 'Night City Neon',
      description: 'Electric cyan & hot magenta',
      colors: {
        primary: 'oklch(0.72 0.20 195)',
        accent: 'oklch(0.65 0.28 330)',
        background: 'oklch(0.08 0.02 260)',
        card: 'oklch(0.12 0.02 260)',
        foreground: 'oklch(0.95 0.01 210)',
        mutedForeground: 'oklch(0.60 0.04 210)',
        border: 'oklch(0.20 0.03 260)',
        secondary: 'oklch(0.15 0.02 260)',
      },
    },
    {
      id: 'corpo-gold',
      name: 'Corpo Gold',
      description: 'Corporate luxury gold & chrome',
      colors: {
        primary: 'oklch(0.78 0.16 85)',
        accent: 'oklch(0.70 0.05 240)',
        background: 'oklch(0.06 0.01 60)',
        card: 'oklch(0.10 0.01 60)',
        foreground: 'oklch(0.92 0.03 85)',
        mutedForeground: 'oklch(0.55 0.03 60)',
        border: 'oklch(0.20 0.04 85)',
        secondary: 'oklch(0.12 0.01 60)',
      },
    },
    {
      id: 'street-punk',
      name: 'Street Punk',
      description: 'Neon pink & acid green',
      colors: {
        primary: 'oklch(0.68 0.26 350)',
        accent: 'oklch(0.72 0.22 145)',
        background: 'oklch(0.04 0.01 350)',
        card: 'oklch(0.08 0.02 350)',
        foreground: 'oklch(0.95 0.02 350)',
        mutedForeground: 'oklch(0.55 0.04 350)',
        border: 'oklch(0.18 0.04 350)',
        secondary: 'oklch(0.10 0.02 350)',
      },
    },
    {
      id: 'netrunner',
      name: 'Netrunner',
      description: 'Electric blue & neon orange',
      colors: {
        primary: 'oklch(0.60 0.22 250)',
        accent: 'oklch(0.70 0.20 55)',
        background: 'oklch(0.05 0.02 250)',
        card: 'oklch(0.09 0.02 250)',
        foreground: 'oklch(0.93 0.02 250)',
        mutedForeground: 'oklch(0.55 0.04 250)',
        border: 'oklch(0.18 0.03 250)',
        secondary: 'oklch(0.12 0.02 250)',
      },
    },
    {
      id: 'militech',
      name: 'Militech',
      description: 'Olive green & amber',
      colors: {
        primary: 'oklch(0.55 0.15 130)',
        accent: 'oklch(0.68 0.16 80)',
        background: 'oklch(0.06 0.02 130)',
        card: 'oklch(0.10 0.02 130)',
        foreground: 'oklch(0.90 0.03 130)',
        mutedForeground: 'oklch(0.55 0.04 130)',
        border: 'oklch(0.18 0.03 130)',
        secondary: 'oklch(0.12 0.02 130)',
      },
    },
  ],
  defaultPresetId: 'night-city-neon',
  defaultColors: {
    primary: 'oklch(0.72 0.20 195)',
    accent: 'oklch(0.65 0.28 330)',
    background: 'oklch(0.08 0.02 260)',
    card: 'oklch(0.12 0.02 260)',
    foreground: 'oklch(0.95 0.01 210)',
    mutedForeground: 'oklch(0.60 0.04 210)',
    border: 'oklch(0.20 0.03 260)',
    secondary: 'oklch(0.15 0.02 260)',
  },
  defaultFonts: {
    heading: "'Orbitron', sans-serif",
    body: "'Exo 2', sans-serif",
    mono: "'Share Tech Mono', monospace",
  },
  animations: [
    { id: 'chromatic', label: 'Chromatic Aberration', defaultEnabled: true, defaultIntensity: 0.3 , hasIntensity: true },
    { id: 'overlayTransition', label: 'Overlay Transition', defaultEnabled: true },
    { id: 'glitch', label: 'Glitch Effect', defaultEnabled: false },
  ],
  customizability: { customColors: true, customFonts: true, adjustEffects: true },
  slots: {
    BackgroundEffects: CyberpunkBackgroundEffects,
    Hero: CyberpunkHero,
    Navigation: CyberpunkNavigation,
    Footer: CyberpunkFooter,
    LoadingScreen: CyberpunkLoadingScreen,
  },
}
