import './styles.css'
import type { ThemePackage } from '@/lib/types'
import AnalogDarkMetalBackgroundEffects from './BackgroundEffects'

export const analogDarkMetalTheme: ThemePackage = {
  id: 'analog-dark-metal',
  name: 'Analog Dark Metal',
  description: 'Heavy metallic aesthetic meets analog warmth – brushed metal, cool neon accents, oscilloscope effects',
  author: 'Neuroklast',
  version: '1.0.0',
  access: 'premium',
  layout: {
    heroVariant: 'default',
    loadingScreen: 'minimal',
    navigationStyle: 'clean',
  },
  typography: {
    heading: "'Rajdhani', sans-serif",
    body: "'Bitter', serif",
    mono: "'IBM Plex Mono', monospace",
  },
  effects: {
    overlayEffects: {
      scanlines: { enabled: true, intensity: 0.15 },
      crt: { enabled: false, intensity: 0 },
      noise: { enabled: true, intensity: 0.6 },
      vignette: { enabled: true, intensity: 0.7 },
      chromatic: { enabled: false, intensity: 0 },
      dotMatrix: { enabled: false, intensity: 0 },
    },
    animationSettings: {
      glitchEnabled: false,
      scanlineEnabled: true,
      chromaticEnabled: false,
      crtEnabled: false,
      noiseEnabled: true,
      circuitBackgroundEnabled: false,
      crtOverlayOpacity: 0,
      crtVignetteOpacity: 0,
      overlayTransitionEnabled: false,
    },
  },
  borderRadius: 0,
  animationsEnabled: true,
  colorPresets: [
    {
      id: 'ice-metal',
      name: 'Ice-Metal',
      description: 'Ice-blue neon on dark brushed steel',
      colors: {
        primary: 'oklch(0.78 0.10 230)',
        accent: 'oklch(0.85 0.08 225)',
        background: 'oklch(0.06 0.01 240)',
        card: 'oklch(0.10 0.01 238)',
        foreground: 'oklch(0.92 0.02 220)',
        mutedForeground: 'oklch(0.55 0.04 230)',
        border: 'oklch(0.20 0.04 235)',
        secondary: 'oklch(0.12 0.02 238)',
      },
    },
    {
      id: 'rust-magenta',
      name: 'Rust-Magenta',
      description: 'Hot magenta accents on oxidized dark metal',
      colors: {
        primary: 'oklch(0.60 0.22 340)',
        accent: 'oklch(0.70 0.20 335)',
        background: 'oklch(0.05 0.02 350)',
        card: 'oklch(0.09 0.02 345)',
        foreground: 'oklch(0.88 0.04 340)',
        mutedForeground: 'oklch(0.50 0.08 340)',
        border: 'oklch(0.18 0.06 345)',
        secondary: 'oklch(0.11 0.03 348)',
      },
    },
    {
      id: 'deep-metal',
      name: 'Deep Metal',
      description: 'Near-black steel with faint grey highlights',
      colors: {
        primary: 'oklch(0.70 0 0)',
        accent: 'oklch(0.80 0 0)',
        background: 'oklch(0.04 0 0)',
        card: 'oklch(0.08 0 0)',
        foreground: 'oklch(0.85 0 0)',
        mutedForeground: 'oklch(0.45 0 0)',
        border: 'oklch(0.16 0 0)',
        secondary: 'oklch(0.10 0 0)',
      },
    },
    {
      id: 'red-circuit',
      name: 'Red Circuit',
      description: 'Aggressive red on deep black – circuit-board traces',
      colors: {
        primary: 'oklch(0.52 0.22 25)',
        accent: 'oklch(0.62 0.24 25)',
        background: 'oklch(0.03 0.01 10)',
        card: 'oklch(0.07 0.02 12)',
        foreground: 'oklch(0.90 0.03 30)',
        mutedForeground: 'oklch(0.48 0.06 20)',
        border: 'oklch(0.16 0.06 18)',
        secondary: 'oklch(0.09 0.03 14)',
      },
    },
  ],
  defaultPresetId: 'ice-metal',
  customizability: { customColors: true, customFonts: true, adjustEffects: true },
  slots: {
    BackgroundEffects: AnalogDarkMetalBackgroundEffects,
  },
}
