import './styles.css'
import type { ThemePackage } from '@/lib/types'
import AnalogDarkMetalBackgroundEffects from './BackgroundEffects'
import AnalogDarkMetalCard from './Card'
import AnalogDarkMetalSectionDivider from './SectionDivider'

export const analogDarkMetalTheme: ThemePackage = {
  id: 'analog-dark-metal',
  name: 'Analog Dark Metal',
  description: 'Dark, heavy, brutal – analog distortion, blackletter typography, raw grain texture',
  author: 'Neuroklast',
  version: '1.0.0',
  access: 'premium',
  layout: {
    heroVariant: 'default',
    loadingScreen: 'minimal',
    navigationStyle: 'clean',
  },
  typography: {
    heading: "'UnifrakturMaguntia', cursive",
    body: "'Bitter', serif",
    mono: "'IBM Plex Mono', monospace",
  },
  effects: {
    overlayEffects: {
      scanlines: { enabled: true, intensity: 0.1 },
      crt: { enabled: false, intensity: 0 },
      noise: { enabled: true, intensity: 0.5 },
      vignette: { enabled: true, intensity: 0.7 },
      chromatic: { enabled: false, intensity: 0 },
      dotMatrix: { enabled: false, intensity: 0 },
    },
    animationSettings: {
      glitchEnabled: false,
      scanlineEnabled: false,
      chromaticEnabled: false,
      crtEnabled: false,
      noiseEnabled: true,
      circuitBackgroundEnabled: false,
      crtOverlayOpacity: 0,
      crtVignetteOpacity: 0,
      overlayTransitionEnabled: false,
    },
  },
  borderRadius: 0,
  animationsEnabled: true,
  colorPresets: [
    {
      id: 'blackened',
      name: 'Blackened',
      description: 'Almost pure black with faint white',
      colors: {
        primary: 'oklch(0.75 0 0)',
        accent: 'oklch(0.88 0 0)',
        background: 'oklch(0.03 0 0)',
        card: 'oklch(0.07 0 0)',
        foreground: 'oklch(0.85 0 0)',
        mutedForeground: 'oklch(0.45 0 0)',
        border: 'oklch(0.15 0 0)',
        secondary: 'oklch(0.10 0 0)',
      },
    },
    {
      id: 'blood-iron',
      name: 'Blood & Iron',
      description: 'Deep crimson on black',
      colors: {
        primary: 'oklch(0.45 0.18 20)',
        accent: 'oklch(0.55 0.20 20)',
        background: 'oklch(0.03 0.01 10)',
        card: 'oklch(0.07 0.01 10)',
        foreground: 'oklch(0.88 0.02 30)',
        mutedForeground: 'oklch(0.48 0.05 20)',
        border: 'oklch(0.15 0.05 15)',
        secondary: 'oklch(0.09 0.02 12)',
      },
    },
    {
      id: 'frost',
      name: 'Frost',
      description: 'Icy blue-white on black',
      colors: {
        primary: 'oklch(0.80 0.06 230)',
        accent: 'oklch(0.90 0.04 225)',
        background: 'oklch(0.04 0.01 240)',
        card: 'oklch(0.08 0.01 240)',
        foreground: 'oklch(0.94 0.02 220)',
        mutedForeground: 'oklch(0.55 0.04 230)',
        border: 'oklch(0.18 0.04 235)',
        secondary: 'oklch(0.11 0.02 238)',
      },
    },
    {
      id: 'pagan-gold',
      name: 'Pagan Gold',
      description: 'Dim gold on near-black',
      colors: {
        primary: 'oklch(0.60 0.10 80)',
        accent: 'oklch(0.70 0.12 83)',
        background: 'oklch(0.04 0.01 50)',
        card: 'oklch(0.08 0.01 50)',
        foreground: 'oklch(0.88 0.05 78)',
        mutedForeground: 'oklch(0.50 0.06 75)',
        border: 'oklch(0.18 0.04 70)',
        secondary: 'oklch(0.10 0.02 55)',
      },
    },
    {
      id: 'funeral-doom',
      name: 'Funeral Doom',
      description: 'Purple-grey on black',
      colors: {
        primary: 'oklch(0.60 0.08 300)',
        accent: 'oklch(0.70 0.10 300)',
        background: 'oklch(0.04 0.01 280)',
        card: 'oklch(0.08 0.01 280)',
        foreground: 'oklch(0.85 0.03 290)',
        mutedForeground: 'oklch(0.50 0.05 295)',
        border: 'oklch(0.17 0.04 285)',
        secondary: 'oklch(0.10 0.02 282)',
      },
    },
  ],
  defaultPresetId: 'blackened',
  customizability: { customColors: true, customFonts: true, adjustEffects: true },
  slots: {
    BackgroundEffects: AnalogDarkMetalBackgroundEffects,
    Card: AnalogDarkMetalCard,
    SectionDivider: AnalogDarkMetalSectionDivider,
  },
}
